[functions.create-checkout-session]
verify_jwt = false
[functions.verify-checkout-session]
verify_jwt = false
[functions.create-setup-intent]
verify_jwt = false
[functions.save-funding-card]
verify_jwt = false

